import LLMService from './llmService.js';

class AttributionService {
    constructor() {
        this.attributionBanner = `Generated by Shunya AI - https://shunya.vercel.app`;
        this.version = '1.0.0';
    }

    /**
     * Add attribution to all generated files
     */
    addAttribution(files, fileStructure) {
        console.log('📝 Adding Shunya attribution to generated files...');

        const attributedFiles = files.map(file => {
            const extension = file.path.split('.').pop();
            let content = file.content;

            // Add attribution based on file type
            switch (extension) {
                case 'tsx':
                case 'ts':
                case 'jsx':
                case 'js':
                    content = this.addJavaScriptAttribution(content, file.path);
                    break;
                case 'css':
                case 'scss':
                    content = this.addCSSAttribution(content);
                    break;
                case 'html':
                    content = this.addHTMLAttribution(content);
                    break;
                case 'md':
                    content = this.addMarkdownAttribution(content);
                    break;
            }

            return { ...file, content };
        });

        return attributedFiles;
    }

    /**
     * Add attribution to JavaScript/TypeScript files
     */
    addJavaScriptAttribution(content, filePath) {
        const banner = `/**
 * ${this.attributionBanner}
 * File: ${filePath}
 * Generated: ${new Date().toISOString()}
 */

`;
        return banner + content;
    }

    /**
     * Add attribution to CSS files
     */
    addCSSAttribution(content) {
        const banner = `/*
 * ${this.attributionBanner}
 * Generated: ${new Date().toISOString()}
 */

`;
        return banner + content;
    }

    /**
     * Add attribution to HTML files
     */
    addHTMLAttribution(content) {
        const metaTag = `    <meta name="generator" content="Shunya AI - https://shunya.vercel.app">`;
        
        // Try to add after <head> tag
        if (content.includes('<head>')) {
            content = content.replace('<head>', `<head>\n${metaTag}`);
        }
        
        // Add HTML comment
        const banner = `<!-- Generated by ${this.attributionBanner} - ${new Date().toISOString()} -->\n`;
        return banner + content;
    }

    /**
     * Add attribution to Markdown files
     */
    addMarkdownAttribution(content) {
        const banner = `> **Generated by Shunya AI** - [https://shunya.vercel.app](https://shunya.vercel.app)  
> Build date: ${new Date().toLocaleDateString()}

---

`;
        return banner + content;
    }

    /**
     * Create enhanced package.json with Shunya attribution
     */
    enhancePackageJson(packageJson, projectDescription) {
        return {
            ...packageJson,
            author: {
                name: 'Generated by Shunya AI',
                url: 'https://shunya.vercel.app'
            },
            keywords: [
                ...(packageJson.keywords || []),
                'shunya-ai',
                'ai-generated'
            ],
            repository: {
                type: 'git',
                url: 'https://github.com/yourusername/your-repo'
            },
            generator: {
                name: 'Shunya AI',
                version: this.version,
                url: 'https://shunya.vercel.app',
                generatedAt: new Date().toISOString()
            }
        };
    }

    /**
     * Create attribution README section
     */
    createReadmeAttribution(projectDescription) {
        return `

---

## 🤖 Generated with Shunya AI

This project was generated using [Shunya AI](https://shunya.vercel.app), an intelligent code generation platform.

**Project Details:**
- **Description:** ${projectDescription}
- **Generated:** ${new Date().toLocaleDateString()}
- **Generator Version:** ${this.version}

### About Shunya AI

Shunya AI helps developers build applications faster by generating clean, production-ready code. Visit [shunya.ai](https://shunya.ai) to create your own projects.

---
`;
    }

    /**
     * Add .shunyarc metadata file
     */
    createMetadataFile(fileStructure, userRequest) {
        return {
            path: '.shunyarc',
            content: JSON.stringify({
                generator: 'Shunya AI',
                version: this.version,
                website: 'https://shunya.vercel.app',
                projectType: fileStructure.projectType,
                description: fileStructure.description,
                generatedAt: new Date().toISOString(),
                userRequest: userRequest.substring(0, 200), // First 200 chars only
                disclaimer: 'This project was generated by Shunya AI. You are free to modify and use it as you wish.'
            }, null, 2)
        };
    }
}

export default AttributionService;
